AWSTemplateFormatVersion: "2010-09-09"
Description: GoldenKiwi Infrastructure - EC2 + S3

# -------------------------
# Parameters
# -------------------------
Parameters:
  EnvironmentName:
    Type: String
    Default: dev

# -------------------------
# Mappings
# -------------------------
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55956c7d316
    eu-north-1:
      AMI: ami-075449515af5df0d1
    eu-west-1:
      AMI: ami-0fed63ea358539e44

# -------------------------
# Resources
# -------------------------
Resources:

  # S3 Bucket
  GoldenKiwiBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-goldennkiwi-bucket"

  # Security Group
  GoldenKiwiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: GoldenKiwi Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  GoldenKiwiEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !FindInMap 
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroupIds:
        - !Ref GoldenKiwiSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-GoldenKiwi-Server"

# -------------------------
# Outputs
# -------------------------
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref GoldenKiwiEC2

  BucketName:
    Description: S3 Bucket Name
    Value: !Ref GoldenKiwiBucket
