version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: dev-lambda-simple
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2