version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Building Lambda package..."
      - cd lambda
      - pip install -r requirements.txt -t .
      - zip -r ../lambda.zip .

artifacts:
  files:
    - lambda.zip